GET http://localhost:9000/users/1
Content-Type: application/json
###

GET https://localhost:9000/users/1
Content-Type: application/json
###


GET http://localhost:8080/users/1
Content-Type: application/json
###

GET https://reqres.in/api/users/2
###