
server:
  port: 8080

spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true    
      default-filters:
        - AddResponseHeader=X-Response-Default-Red, Default-Blue
        
      routes:
      - id: r1
        uri: https://HOSTNAME
        # uri: https://reqres.in
        predicates:
        - Path=/users/1
        filters:
        - SetPath=/api/users/1
  
logging:
  level:
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.security: TRACE
