
server:
  port: 8080
  http.port: 80
  ssl:
    enabled: false
    key-store: classpath:ssl/keystore.jks.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: localhost

spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true    
      default-filters:
        - AddResponseHeader=X-Response-Default-Red, Default-Blue
        
      routes:
      - id: r1
        uri: https://HOSTNAME
        # uri: https://reqres.in
        predicates:
        - Path=/users/1
        filters:
        - SetPath=/api/users/1
  
logging:
  level:
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.security: TRACE
